/**
 * content.ts
 *
 * HOW IT WORKS:
 *
 * 1. MANIFEST  — loaded from src/content/_manifest.json (generated by
 *    vite-plugin-content-manifest at build/dev start).  This is a few KB of
 *    JSON containing only frontmatter (title, slug, category ...).  It is
 *    imported eagerly so the sidebar and search work instantly.
 *
 * 2. ARTICLE BODIES — every .md file is registered as a lazy Vite chunk via
 *    import.meta.glob with eager:false.  When getArticleAsync(slug) is called,
 *    only that one file is fetched over the network (then cached in memory).
 *    The other 99+ files are never downloaded until the user actually visits them.
 *
 * This means the initial JS bundle contains ZERO markdown content.
 */

import { mindmapSlugSet } from './mindmap';
import _manifest from '../content/_manifest.json';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ArticleMeta {
  title: string;
  slug: string;
  description: string;
  category: string;
  order: number;
  hasPractice: boolean;
  hasMindmap: boolean;
}

export interface Article extends ArticleMeta {
  content: string;
}

export interface PracticeQuestion {
  id: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  question: string;
  answer: string;
}

export interface PracticeMeta {
  title: string;
  articleSlug: string;
  difficulty: string;
  estimatedTime: string;
  totalQuestions: number;
}

export interface PracticeArticle extends PracticeMeta {
  questions: PracticeQuestion[];
}

// ─── Lazy file loaders — Vite splits each .md into its own chunk ──────────────
// eager: false → file is NOT included in the main bundle.
// Calling the loader function fetches only that one file from the network.

const articleLoaders = import.meta.glob('../content/*.md', {
  query: '?raw',
  import: 'default',
  eager: false,
}) as Record<string, () => Promise<string>>;

const practiceLoaders = import.meta.glob('../content/practice/*.md', {
  query: '?raw',
  import: 'default',
  eager: false,
}) as Record<string, () => Promise<string>>;

const mindmapLoaders = import.meta.glob('../content/mindmap/*.md', {
  query: '?raw',
  import: 'default',
  eager: false,
}) as Record<string, () => Promise<string>>;

// ─── In-memory cache — each file fetched at most once per session ─────────────

const cache: Record<string, string> = {};

async function loadRaw(
  loaders: Record<string, () => Promise<string>>,
  path: string
): Promise<string | null> {
  if (cache[path] !== undefined) return cache[path];
  const loader = loaders[path];
  if (!loader) return null;
  const raw = await loader();
  cache[path] = raw;
  return raw;
}

// ─── Frontmatter parser (used only for lazily-loaded bodies) ─────────────────

function parseFrontmatter(raw: string): { meta: Record<string, string>; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: raw };
  const meta: Record<string, string> = {};
  match[1].split('\n').forEach((line) => {
    const i = line.indexOf(':');
    if (i === -1) return;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  });
  return { meta, body: match[2] };
}

// ─── Manifest (from JSON — no markdown content, just metadata) ───────────────

// _manifest.json is generated by vite-plugin-content-manifest.
// We re-apply mindmapSlugSet at runtime in case the plugin was not run yet
// (e.g. first clone before running vite dev).
const manifestData = (_manifest as ArticleMeta[]).map((item) => ({
  ...item,
  hasMindmap: item.hasMindmap || mindmapSlugSet.has(item.slug),
}));

export function getManifest(): ArticleMeta[] {
  return manifestData;
}

// ─── Article — async, lazy body ───────────────────────────────────────────────

export async function getArticleAsync(slug: string): Promise<Article | null> {
  const path = `../content/${slug}.md`;
  const raw  = await loadRaw(articleLoaders, path);
  if (!raw) return null;

  const { meta, body } = parseFrontmatter(raw);
  const meta2 = manifestData.find((m) => m.slug === slug);

  return {
    slug,
    title:       meta2?.title       ?? meta.title       ?? slug,
    description: meta2?.description ?? meta.description ?? '',
    category:    meta2?.category    ?? meta.category    ?? 'General',
    order:       meta2?.order       ?? parseInt(meta.order || '99', 10),
    hasPractice: meta2?.hasPractice ?? false,
    hasMindmap:  meta2?.hasMindmap  ?? false,
    content: body.trim(),
  };
}

// ─── Practice article — async, lazy ───────────────────────────────────────────

function parsePracticeQuestions(body: string): PracticeQuestion[] {
  const questions: PracticeQuestion[] = [];
  const blocks = body.split('<!-- QUESTION -->').slice(1);

  blocks.forEach((block, idx) => {
    const [questionPart, rest] = block.split('<!-- ANSWER -->');
    if (!questionPart || !rest) return;
    const [answerPart] = rest.split('<!-- END -->');
    if (!answerPart) return;

    const lines = questionPart.trim().split('\n');
    let difficulty: PracticeQuestion['difficulty'] = 'Medium';
    const tags: string[] = [];
    let questionStart = 0;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.startsWith('difficulty:')) {
        const d = line.replace('difficulty:', '').trim();
        if (d === 'Easy' || d === 'Medium' || d === 'Hard') difficulty = d;
        questionStart = i + 1;
      } else if (line.startsWith('tags:')) {
        tags.push(...line.replace('tags:', '').trim().split(',').map((t) => t.trim()));
        questionStart = i + 1;
      } else if (line !== '') {
        break;
      }
    }

    const questionText = lines.slice(questionStart).join('\n').trim();
    const answerText   = answerPart.trim();
    if (questionText) {
      questions.push({ id: idx + 1, difficulty, tags, question: questionText, answer: answerText });
    }
  });

  return questions;
}

export async function getPracticeArticle(slug: string): Promise<PracticeArticle | null> {
  const path = `../content/practice/${slug}.md`;
  const raw  = await loadRaw(practiceLoaders, path);
  if (!raw) return null;

  const { meta, body } = parseFrontmatter(raw);
  const questions      = parsePracticeQuestions(body) ?? [];

  return {
    title:          meta.title          || `${slug} — Practice`,
    articleSlug:    meta.articleSlug    || slug,
    difficulty:     meta.difficulty     || 'Intermediate',
    estimatedTime:  meta.estimatedTime  || '20 mins',
    totalQuestions: questions.length,
    questions,
  };
}

// ─── Mindmap raw loader (for MindMapPage) ────────────────────────────────────

export async function getMindmapRaw(slug: string): Promise<string | null> {
  return loadRaw(mindmapLoaders, `../content/mindmap/${slug}.md`);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getCategories(manifest: ArticleMeta[]): Record<string, ArticleMeta[]> {
  return manifest.reduce<Record<string, ArticleMeta[]>>((acc, item) => {
    if (!acc[item.category]) acc[item.category] = [];
    acc[item.category].push(item);
    return acc;
  }, {});
}

// ─── Exports used app-wide ────────────────────────────────────────────────────

/**
 * Sync shim — returns metadata only (no content body).
 * Kept for backward compatibility with MindMapPage and PracticePage
 * which only need article.title / hasPractice / hasMindmap etc.
 * DocsPage uses getArticleAsync() for the full content.
 */
export function getArticle(slug: string): ArticleMeta | null {
  return manifestData.find((m) => m.slug === slug) ?? null;
}

export const MANIFEST       = getManifest();
export const CATEGORIES     = getCategories(MANIFEST);
export const CATEGORY_ORDER = [
  'Low Level Design',
  'High Level Design',
  'Networking',
  'Introduction',
  'Guides',
  'Reference',
  'Community',
];